spring:
  datasource:
    article:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?useSSL=false&characterEncoding=utf-8
      username: root
      password: 123456

    user:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=utf-8
      username: root
      password: 123456


server:
  port: 9090
#mybatis:
#  mapper-locations: classpath:mapper/*/*.xml
##  type-aliases-package: com.yjs.example.springbootmybatis


